### ISSUE TITLE
How can I get args and argv when I develop

### ISSUE THREAD

**Issue by xavieryang007** [jphp-group/jphp#320]
Hi.
when I build it into a jar.I can get the args and argv. But if I use jppm start ,I can get them.How can I get them when I developing

**Comment by MWGuy** [comment]
For set command line arguments add this into ``package.php.yml``: 
```yaml
...

app:
   args: "foo bar"
```
